package com.murat.todolist.ui.tasks;

public enum TaskFilterType {
    All_TASK,
    ACTIVE_TASKS,
    COMPLETED_TASKS,
    EXPIRED_TASKS,
    ORDER_BY_NAME_ASC_TASKS,
    ORDER_BY_NAME_DESC_TASKS,
    ORDER_BY_CREATE_DATE_ASC_TASKS,
    ORDER_BY_CREATE_DATE_DESC_TASKS,
    ORDER_BY_DEADLINE_DATE_ASC_TASKS,
    ORDER_BY_DEADLINE_DATE_DESC_TASKS,
    ORDER_BY_STATUS_ASC_TASKS,
    ORDER_BY_STATUS_DESC_TASKS;
}
